attempt to fix broken shell issues for empty for loops when the validator isn't configured to be compiled in

diff --git a/dnssec-tools/Makefile.in b/dnssec-tools/Makefile.in
--- a/dnssec-tools/Makefile.in
+++ b/dnssec-tools/Makefile.in
@@ -1,8 +1,22 @@
+prefix=@prefix@
+exec_prefix=@exec_prefix@
+bindir=@bindir@
+sbindir=@sbindir@
+libdir=@libdir@
+datadir=@datadir@
+includedir=@includedir@
+mandir=@mandir@
+#man1dir=@man1dir@
+#man3dir=@man3dir@
+#man5dir=@man5dir@
+#man8dir=@man8dir@
+
 PERLDIRS=tools/modules tools/donuts tools/mapper tools/scripts \
          tools/dnspktflow tools/maketestzone tools/etc tools/drawvalmap
 PERLARGS=@PERLARGS@
 SUBDIRS=@DNSSEC_SUBDIRS@
 INSTALLDIRS=$(prefix) $(exec_prefix) $(bindir) $(sbindir) $(libdir) $(datadir) $(includedir) $(mandir) $(man1dir) $(man3dir) $(man5dir) $(man8dir)		
+QUIET=@
 
 all: makeit
 
@@ -17,15 +31,15 @@ clean: perlclean subdirclean
 distclean: clean configclean
 
 nextstepinstructions:
-	@echo ""
-	@echo "**********************************************************************"
-	@echo "** NEXT: Please run 'dtinitconf' in order to set up the required"
-	@echo "**       $(prefix)/etc/dnssec/dnssec-tools.conf file"
-	@echo "**********************************************************************"
-	@echo ""
+	$(QUIET)echo ""
+	$(QUIET)echo "**********************************************************************"
+	$(QUIET)echo "** NEXT: Please run 'dtinitconf' in order to set up the required"
+	$(QUIET)echo "**       $(prefix)/etc/dnssec/dnssec-tools.conf file"
+	$(QUIET)echo "**********************************************************************"
+	$(QUIET)echo ""
 
 makedirectories:
-	@for i in $(INSTALLDIRS) ; do \
+	$(QUIET)for i in $(INSTALLDIRS) ; do \
 		if test ! -d $$i ; then \
 			echo "creating directory $$i/" \
 			$(MKPATH) $$I ; \
@@ -36,32 +50,38 @@ makedirectories:
 #
 
 subdirmake:
-	@for i in $(SUBDIRS) ; do \
-	  (cd $$i ; make ) ; \
-	  if test $$? != 0 ; then \
-	     exit 1 ; \
-	  fi  \
-         done
+	$(QUIET)if test "x$(SUBDIRS)" != "xnone" ; then \
+	  for i in $(SUBDIRS) ; do \
+	    (cd $$i ; make ) ; \
+	    if test $$? != 0 ; then \
+	       exit 1 ; \
+	    fi  \
+          done \
+	fi
 
 subdirinstall:
-	@for i in $(SUBDIRS) ; do \
-	  (cd $$i ; make install ) ; \
-	  if test $$? != 0 ; then \
-	     exit 1 ; \
-	  fi  \
-         done
+	$(QUIET)if test "x$(SUBDIRS)" != "xnone" ; then \
+	  for i in $(SUBDIRS) ; do \
+	   (cd $$i ; make install ) ; \
+	   if test $$? != 0 ; then \
+	      exit 1 ; \
+	   fi  \
+          done \
+	fi
 
 subdirclean:
-	@for i in $(SUBDIRS) ; do \
-	  (cd $$i ; make clean ) ; \
-         done
+	$(QUIET)if test "x$(SUBDIRS)" != "xnone" ; then \
+	  $(QUIET)for i in $(SUBDIRS) ; do \
+	    (cd $$i ; make clean ) ; \
+          done \
+	fi
 
 #
 # Perl system build rules
 #
 
 perlmake:
-	@for i in $(PERLDIRS) ; do \
+	$(QUIET)for i in $(PERLDIRS) ; do \
 	  (cd $$i ; make ) ; \
 	  if test $$? != 0 ; then \
 	     exit 1 ; \
@@ -69,14 +89,14 @@ perlmake:
          done
 
 perlmakefiles:
-	@for i in $(PERLDIRS) ; do \
+	$(QUIET)for i in $(PERLDIRS) ; do \
 	  if test ! -f $$i/Makefile ; then \
 	    (cd $$i ; perl Makefile.PL $(PERLARGS)) ; \
           fi ; \
          done
 
 perlinstall:
-	@for i in $(PERLDIRS) ; do \
+	$(QUIET)for i in $(PERLDIRS) ; do \
 	  (cd $$i ; make install ) ; \
 	  if test $$? != 0 ; then \
 	     exit 1 ; \
@@ -84,7 +104,7 @@ perlinstall:
          done
 
 perlclean:
-	@for i in $(PERLDIRS) ; do \
+	$(QUIET)for i in $(PERLDIRS) ; do \
 	  (cd $$i ; make clean ) ; \
          done
 
