Made nsec3 and dlv configure logic similar to that of ipv6
git-svn-id: https://www.dnssec-tools.org/svn/dnssec-tools/trunk@3150 c4029f9c-b713-0410-a448-fae9e31a314a

diff --git a/dnssec-tools/validator/configure b/dnssec-tools/validator/configure
--- a/dnssec-tools/validator/configure
+++ b/dnssec-tools/validator/configure
@@ -1046,7 +1046,8 @@ Optional Packages:
 Miscellaneous:
   --with-defaults         Use defaults for prompted values.
   --with-cflags=CFLAGS    use CFLAGS as compile time arguments.
-  --with-nsec3            Enable NSEC3.
+  --with-nsec3            Enable nsec3 support.
+  --with-dlv            Enable DLV support.
   --with-ipv6             Enable IPv6 support.
   --with-perl-perl-args=ARGS           Add ARGS to building perl Makefiles.
   --with-openssl=PATH     Look for openssl in PATH/{lib,include}.
@@ -3258,7 +3259,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3261 "configure"' > conftest.$ac_ext
+  echo '#line 3262 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4748,7 +4749,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4751:" \
+echo "$as_me:4752:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5811,11 +5812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5814: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5818: \$? = $ac_status" >&5
+   echo "$as_me:5819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6079,11 +6080,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6082: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6083: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6086: \$? = $ac_status" >&5
+   echo "$as_me:6087: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6183,11 +6184,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6186: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6187: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6190: \$? = $ac_status" >&5
+   echo "$as_me:6191: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7652,7 +7653,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 7655 "configure"' > conftest.$ac_ext
+    echo '#line 7656 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8549,7 +8550,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8552 "configure"
+#line 8553 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8649,7 +8650,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8652 "configure"
+#line 8653 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10989,11 +10990,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10992: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10993: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10996: \$? = $ac_status" >&5
+   echo "$as_me:10997: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11093,11 +11094,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11096: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11097: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11100: \$? = $ac_status" >&5
+   echo "$as_me:11101: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11629,7 +11630,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11632 "configure"' > conftest.$ac_ext
+    echo '#line 11633 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12684,11 +12685,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12687: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12688: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12691: \$? = $ac_status" >&5
+   echo "$as_me:12692: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12788,11 +12789,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12795: \$? = $ac_status" >&5
+   echo "$as_me:12796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14237,7 +14238,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14240 "configure"' > conftest.$ac_ext
+    echo '#line 14241 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15012,11 +15013,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15015: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15019: \$? = $ac_status" >&5
+   echo "$as_me:15020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15280,11 +15281,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15283: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15284: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15287: \$? = $ac_status" >&5
+   echo "$as_me:15288: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15384,11 +15385,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15387: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15388: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15391: \$? = $ac_status" >&5
+   echo "$as_me:15392: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16853,7 +16854,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 16856 "configure"' > conftest.$ac_ext
+    echo '#line 16857 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18345,11 +18346,69 @@ esac
 # Check whether --with-nsec3 or --without-nsec3 was given.
 if test "${with_nsec3+set}" = set; then
   withval="$with_nsec3"
-  cat >>confdefs.h <<\_ACEOF
+  nsec3="$withval"
+else
+  nsec3="no"
+fi;
+# Check whether --enable-nsec3 or --disable-nsec3 was given.
+if test "${enable_nsec3+set}" = set; then
+  enableval="$enable_nsec3"
+  { { echo "$as_me:$LINENO: error:  Invalid option. Use --with-nsec3/--without-nsec3 instead " >&5
+echo "$as_me: error:  Invalid option. Use --with-nsec3/--without-nsec3 instead " >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+if test "$nsec3" = "yes"; then
+    cat >>confdefs.h <<\_ACEOF
 #define LIBVAL_NSEC3 1
 _ACEOF
 
+
+  cat >> configure-summary << EOF
+  NSEC3 support                  : Yes
+EOF
+
+else
+
+  cat >> configure-summary << EOF
+  NSEC3 support                  : No
+EOF
+
+fi
+
+
+
+
+# Check whether --with-dlv or --without-dlv was given.
+if test "${with_dlv+set}" = set; then
+  withval="$with_dlv"
+  dlv="$withval"
+else
+  dlv="no"
 fi;
+# Check whether --enable-dlv or --disable-dlv was given.
+if test "${enable_dlv+set}" = set; then
+  enableval="$enable_dlv"
+  { { echo "$as_me:$LINENO: error:  Invalid option. Use --with-dlv/--without-dlv instead " >&5
+echo "$as_me: error:  Invalid option. Use --with-dlv/--without-dlv instead " >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+if test "$dlv" = "yes"; then
+    cat >>confdefs.h <<\_ACEOF
+#define LIBVAL_DLV 1
+_ACEOF
+
+
+  cat >> configure-summary << EOF
+  DLV support                    : Yes
+EOF
+
+else
+
+  cat >> configure-summary << EOF
+  DLV support                    : No
+EOF
+
+fi
 
 
 
