Add support for SHA-256 DS algorithm

diff --git a/dnssec-tools/validator/configure b/dnssec-tools/validator/configure
--- a/dnssec-tools/validator/configure
+++ b/dnssec-tools/validator/configure
@@ -18602,6 +18602,83 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for SHA256_Init in -lcrypto" >&5
+echo $ECHO_N "checking for SHA256_Init in -lcrypto... $ECHO_C" >&6
+if test "${ac_cv_lib_crypto_SHA256_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypto  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SHA256_Init ();
+int
+main ()
+{
+SHA256_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypto_SHA256_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_crypto_SHA256_Init=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_SHA256_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_crypto_SHA256_Init" >&6
+if test $ac_cv_lib_crypto_SHA256_Init = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_SHA_256 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: WARNING: Need openssl version > 0.9.8 for SHA-256 support" >&5
+echo "$as_me: WARNING: Need openssl version > 0.9.8 for SHA-256 support" >&2;}
+
+fi
+
+
+
 echo "$as_me:$LINENO: checking for inet_ntop in -lnsl" >&5
 echo $ECHO_N "checking for inet_ntop in -lnsl... $ECHO_C" >&6
 if test "${ac_cv_lib_nsl_inet_ntop+set}" = set; then
