attempt to carefully define gethostbyname: take 1
git-svn-id: https://www.dnssec-tools.org/svn/dnssec-tools/trunk@4343 c4029f9c-b713-0410-a448-fae9e31a314a

diff --git a/dnssec-tools/validator/configure b/dnssec-tools/validator/configure
--- a/dnssec-tools/validator/configure
+++ b/dnssec-tools/validator/configure
@@ -23086,10 +23086,11 @@ _ACEOF
 fi
 
 
+found_gethostbyaddr=0
 
 
-echo "$as_me:$LINENO: checking whether gethostbyaddr expects socklen_t or an int" >&5
-echo $ECHO_N "checking whether gethostbyaddr expects socklen_t or an int... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for the proper gethostbyaddr prototype" >&5
+echo $ECHO_N "checking for the proper gethostbyaddr prototype... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -23141,9 +23142,10 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: result: int" >&5
 echo "${ECHO_T}int" >&6
   cat >>confdefs.h <<\_ACEOF
-#define GETHOSTBYADDR_USES_INT 1
+#define GETHOSTBYADDR_USES_CHAR_INT 1
 _ACEOF
 
+  found_gethostbyaddr=1
 
 else
   echo "$as_me: failed program was:" >&5
@@ -23157,6 +23159,154 @@ echo "${ECHO_T}socklen_t" >&6
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+
+if test $found_gethostbyaddr == 0 ; then
+
+
+echo "$as_me:$LINENO: checking for the proper gethostbyaddr prototype" >&5
+echo $ECHO_N "checking for the proper gethostbyaddr prototype... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <netdb.h>
+#include <sys/socket.h>
+
+int
+main ()
+{
+
+struct hostent *gethostbyaddr(const void *addr, socklen_t len, int type);
+
+int i = 1;
+
+/* struct hostent *testit = gethostbyaddr("127.0.0.1", int len, int type) */
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: void and socklen_t" >&5
+echo "${ECHO_T}void and socklen_t" >&6
+  cat >>confdefs.h <<\_ACEOF
+#define GETHOSTBYADDR_USES_VOID_SOCKLEN 1
+_ACEOF
+
+  found_gethostbyaddr=1
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+  echo "$as_me:$LINENO: result: socklen_t" >&5
+echo "${ECHO_T}socklen_t" >&6
+
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+
+if test $found_gethostbyaddr == 0 ; then
+
+
+echo "$as_me:$LINENO: checking for the proper gethostbyaddr prototype" >&5
+echo $ECHO_N "checking for the proper gethostbyaddr prototype... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <netdb.h>
+#include <sys/socket.h>
+
+int
+main ()
+{
+
+struct hostent *gethostbyaddr(const void *addr, int len, int type);
+
+int i = 1;
+
+/* struct hostent *testit = gethostbyaddr("127.0.0.1", int len, int type) */
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: void and int" >&5
+echo "${ECHO_T}void and int" >&6
+  cat >>confdefs.h <<\_ACEOF
+#define GETHOSTBYADDR_USES_VOID_INT 1
+_ACEOF
+
+  found_gethostbyaddr=1
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+  echo "$as_me:$LINENO: result: socklen_t" >&5
+echo "${ECHO_T}socklen_t" >&6
+
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
 
 found_getnameinfo=0
 
